language: node_js
node_js:
  - 10
deploy:
  provider: heroku
  api_key:
    secure: kCv4zk3ofQS3Q5qCjha61SjyEY76ZhStmRbONwJsDIq4k4TLBppM9Piii1VrLg+SRfcu6IoTfurr5c8257elhBBPULFjBD0aXsN+we8j+1Zgve4OCyzRIRbacgc7JunVTyt/OYHCS2FpQRUapAL0hMe3h+udcnw/+A5uEbBAXSxwyMYbxlHC4F4Gsb1aJ1fPy8YPMfsOjp/RcGrUjxScyTva0h+HrZCcwWvFlXqW//keGwhaS8KkJ83GwOaO7dFc3nHfhrnaEnXo/QwCiWZrsNnrfCwNlZS4fpCQbZmjIwE9xo1o+cQTxF6zIPcXWUbxkpOlkAiwCB5dB8jhoCZ7MDObbDN/zDs5AImLQd9uwwnv6CioK5Cs6Uv1UzRP71mUBhLWuYpTKACVg4OesBQ90aJ2uu3N0abBXCDNRsXJeebQ1gORof2Ch8lvu+N/IbxMeskSyrEqHlhqfqw6TwcteRpXFM5CIpCQRteH/L8M9c23S1awWy6hCzxUH1lvkK7QnVffFF/ezmKFmUGt3NJWY9daU+jsJy9h60rCrEhUMm2pQityc3y+vdovNcLnauOK+39qv4bfnfmRgSbSOjQeRleFTfjpjUXtfSKymVlsDuwoZCLhTaslKmEC6e97MnFpO0Ok/okFu7iFrJ2RiZwaaxmNFoFrGJXv6jYijelH4yg=
  app: gear-control
  on:
    repo: Rofrtd/Gear-Control
